### ISSUE TITLE
Adding wind effect to other objects

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#128]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/128)) by Brian Bingham (Bitbucket: [brian_bingham](https://bitbucket.org/%7B9cdea257-248f-486e-8858-49d8485a916f%7D/)).**

----------------------------------------
Currently the WAM-V is the only object affected by wind.  Other objects are affected in different ways:

* For buoy makers and totems the wind induces translation \(moving relative to the anchor\) and attitude changes \(oscillating pitch and roll\).
* For docks, the wind can cause translation and orientation \(yaw\) changes.

At this point, I recommend that this be considered for addition after the VRX competition, but would like it to be on the list.

**Comment by acxz** [comment]
Duplicate of #195 ?
in favor of closing this issue due to #195 having more discussion

**Comment by M1chaelM** [comment]
I agree. Closing this as a duplicate of #195
