### ISSUE TITLE
Testing for computational issues

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#136]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/136)) by Brian Bingham (Bitbucket: [brian_bingham](https://bitbucket.org/%7B9cdea257-248f-486e-8858-49d8485a916f%7D/)).**

----------------------------------------
With 1.1 we are allowing teams a pretty hefty set of cameras and two lidars.  We also added some buoyancy elements that may soak up some more compute cycles.  We should generate some example configurations and worlds to serve as worst case examples to evaluate the ability for VRX to run in real-time on our stated systems specs: [https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/wiki/system\_requirements](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/wiki/system_requirements)

**Comment by M1chaelM** [comment]
@bsb808 and @caguero Since it has been a couple of years now, I propose to outsource this task to the community. I will close it for now, and we can reopen it if we receive any reports that VRX is not running properly using the specs we provided.
