### ISSUE TITLE
Investigate oyaml dependency

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#151]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/151)) by Tyler Lum (Bitbucket: [tylerlum](https://bitbucket.org/%7B305d9368-23ba-4f72-b1d4-7d17d2a062d8%7D/)).**

----------------------------------------
**Description**

Currently, we are using oyaml for generating custom worlds and wamvs \(generate\_wamv.launch and generate\_worlds.launch\). This requires users to run `pip install oyaml` as per [https://pypi.org/project/oyaml/](https://pypi.org/project/oyaml). However, `pip` can lead to headaches. We should investigate if this is needed or not, and perhaps just use pyyaml.

**Where this is used**

```
➜  vrx_gazebo grep -r "yaml" | grep import
src/vrx_gazebo_python/generator_scripts/utils.py:import yaml
src/vrx_gazebo_python/generator_scripts/world_generator/generate_worlds.py:import oyaml as yaml
src/vrx_gazebo_python/generator_scripts/wamv_config/compliance.py:import yaml
```

**Comment by M1chaelM** [comment]
This dependency was not needed and has been removed from the installation instructions.
