### ISSUE TITLE
Getting error while launching  roslaunch vrx_gazebo vrx.launch

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#154]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/154)) by Anonymous.**

----------------------------------------
Unable to find uri[model://ocean_waves].
I am using ros melodic gazebo 9

**Comment by HashirZahir** [comment]
I believe this issue can be closed.

**Comment by caguero** [comment]
I'm closing this issue. Please reopen if you still have the error with the latest released version.
