### ISSUE TITLE
usv_dynamics_plugin segfaults

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#158]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/158)) by Anonymous.**

----------------------------------------
I am trying to integrate vrx simulation in to a [PX4 software in the loop simulation(SITL)](https://dev.px4.io/v1.9.0/en/simulation/gazebo.html)

I have written a sdf file which contains the `usv_gazebo_dynamics_plugin` with a mavlink plugin in order to be able to run it with the PX4 rover firmware.

However, it segfaults when being launched. The line where it segfaults seems to be this line: https://github.com/osrf/vrx/blob/e76f588531c7c397f72e14a136f665e340dda7bf/usv_gazebo_plugins/src/usv_gazebo_dynamics_plugin.cc#L320

I added the following lines in my sdf file for the boat.
```
      <plugin name="usv_dynamics" filename="libusv_gazebo_dynamics_plugin.so">
        <bodyName>base_link</bodyName>
        <!-- Length discretization, AKA, "N" -->
        <length_n>2</length_n>
        <!-- Wave model -->
        <wave_model>ocean_waves</wave_model>
      </plugin>
```
Is there some other plugin that needs to be launched prior to launching the dyanamics plugin?

**Comment by mzahana** [comment]
Hi @osrf-migration . I am trying to use vrx with PX4. Is there documentation on how to do that?
Thanks

**Comment by scpeters** [comment]
`osrf-migration` is a bot that imported this issue from bitbucket, so you'll need to ask someone else. I don't know the answer to your question
