### ISSUE TITLE
how to write the code to drive the boat go ahead?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#159]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/159)) by Anonymous.**

----------------------------------------
can anyone show me the sample code(c++)? the vrx tutorial about driving seems it's of little practical use

**Comment by Roboticistprogrammer** [comment]
> I’ve added a short section of the current [driving tutorial](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/wiki/tutorials/Driving) to provide some details of interface options to publish to the ROS network. If you are new to ROS I would recommend using your tool of choice (C++?)

Any chance you could guide me toward driving_tutorial for VRX, I can't find it on BitBucket.

I have my own model visualized in nbpark.sdf, but I can't drive the model. (I am using Ros2-Humble)
