### ISSUE TITLE
Relocation of repository due to ending support of Mercurial

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#197]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/197)) by Hashir Zahir (Bitbucket: [hzahir](https://bitbucket.org/%7B0033cdb9-ea6e-4c6a-a9ad-d462a485643d%7D/)).**

----------------------------------------
As most of us may know, [Bitbucket is ending support for Mercurial](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket) and all mercurial repositories will be removed by June 1, 2020, which is less than 50 days away. Where is the location of next VRX simulator repository?

**Comment by caguero** [comment]
The code has been migrated, see:

https://github.com/osrf/vrx
https://github.com/osrf/vrx-docker
https://github.com/osrf/vrx-events

I'm working on migrating the wiki now.

**Comment by caguero** [comment]
Migration done!
