### ISSUE TITLE
gazebo plugin

### ISSUE THREAD

**Issue by qycqycqyc** [osrf/vrx#205]
Could you tell me How to write gazebo plugin by myself,I want to learn it to write my own plugins.I had learnt gazebo tutorials,but there are not grammars.
By the way,could you tell me how to delete robotNamespace parameter in your usv_gazebo_plugins.
Thanks!

**Comment by caguero** [comment]
@qycqycqyc Please do not replicate the same issue in multiple repositories. Let's continue the conversation in https://github.com/osrf/gazebo/issues/2750
