### ISSUE TITLE
when i roslaunch wamv_gazebo rviz_vrx.launch  the wamv/odom frame is flying

### ISSUE THREAD

**Issue by qycqycqyc** [osrf/vrx#211]
![2020-06-30 17-38-54屏幕截图](https://user-images.githubusercontent.com/48520573/86112136-2c893000-bafa-11ea-878d-8094e7824ae7.png)
how could i do to lock the odom frame?

**Comment by qycqycqyc** [comment]
![2020-06-30 17-51-45屏幕截图](https://user-images.githubusercontent.com/48520573/86112326-69552700-bafa-11ea-9b25-8de0b4fe38a7.png)

**Comment by HashirZahir** [comment]
I believe this behaviour can be adjusted if you follow the `robot_localization` docs where its mentioned here that setting `~zero_altitude` to true will ensure that the `pose.z` value is always 0. Edit the parameters from here:

[localization_example.launch](https://github.com/osrf/vrx/blob/master/wamv_gazebo/launch/localization_example.launch)

Hope that fixes the issue, if so, please close this issue.

**Comment by qycqycqyc** [comment]
@HashirZahir I am sorry to say it does not work.

here it is what i do in localization_example.launch

<?xml version="1.0"?>

<launch>
  
  <node pkg="robot_state_publisher" type="robot_state_publisher" name="rob_st_pub">
    </node>

  
  <node pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher">
    <param name="gui" value="false" />
  </node>

  
  <node pkg="robot_localization" type="ekf_localization_node"
        name="ekf_localization" clear_params="false">
    <param name="sensor_timeout" value="2.0"/>
    <param name="two_d_mode" value="false"/>
    <param name="map_frame" value="map"/>
    <param name="odom_frame" value="odom"/>
    <param name="base_link_frame" value="base_link"/>
    <param name="world_frame" value="odom"/>
    <param name="publish_tf" value="true"/>
     <param name="~zero_altitude" value="true"/>
    <param name="frequency" value="60"/>
    <param name="imu0" value="/sensors/imu/imu/data"/>
    
    <rosparam param="imu0_config">[false, false, false,
                                   true,  true,  true,
                                   false,  false,  false,
                                   true,  true,  true,
                                   true,  true,  true]</rosparam>
    <param name="imu0_differential" value="false"/>
    <param name="imu0_remove_gravitational_acceleration" value="true"/>

    <param name="odom0" value="/robot_localization/odometry/gps"/>
    
    <rosparam param="odom0_config">[true,  true,  true,
                                   false, false, false,
                                   false, false, false,
                                   false, false, false,
                                   false, false, false]</rosparam>

    <param name="odom0_differential" value="false"/>
    <param name="smooth_lagged_data" value="true"/>
  </node>

  
  <node pkg="robot_localization" type="navsat_transform_node"
        name="navsat_transform_node" respawn="true" output="screen">
         <param name="frequency" value="60"/>
    <param name="magnetic_declination_radians" value="0"/>
    <param name="broadcast_utm_transform" value="true"/>
    <param name="~zero_altitude" value="true"/>
    <param name="wait_for_datum" value="true"/>
    <param name="use_odometry_yaw" value="true"/>
    <rosparam param="datum">[21.30996, -157.8901]</rosparam>
    <param name="yaw_offset" value="0"/>
    <param name="publish_filtered_gps" value="true"/>
    <remap to="/sensors/gps/gps/fix" from="/robot_localization/gps/fix" />
  </node>
</launch>

![2020-07-11 20-25-26屏幕截图](https://user-images.githubusercontent.com/48520573/87224102-1fe7c000-c3b5-11ea-88eb-5eabab4df91e.png)

**Comment by qycqycqyc** [comment]
<?xml version="1.0"?>

<launch>
  
  <node pkg="robot_state_publisher" type="robot_state_publisher" name="rob_st_pub">
    </node>

  
  <node pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher">
    <param name="gui" value="false" />
  </node>

  
  <node pkg="robot_localization" type="ekf_localization_node"
        name="ekf_localization" clear_params="false">
    <param name="sensor_timeout" value="2.0"/>
    <param name="two_d_mode" value="false"/>
    <param name="map_frame" value="map"/>
    <param name="odom_frame" value="odom"/>
    <param name="base_link_frame" value="base_link"/>
    <param name="world_frame" value="odom"/>
    <param name="publish_tf" value="true"/>
     <param name="~zero_altitude" value="true"/>
    <param name="frequency" value="60"/>
    <param name="imu0" value="/sensors/imu/imu/data"/>
    
    <rosparam param="imu0_config">[false, false, false,
                                   true,  true,  true,
                                   false,  false,  false,
                                   true,  true,  true,
                                   true,  true,  true]</rosparam>
    <param name="imu0_differential" value="false"/>
    <param name="imu0_remove_gravitational_acceleration" value="true"/>

    <param name="odom0" value="/robot_localization/odometry/gps"/>
    
    <rosparam param="odom0_config">[true,  true,  true,
                                   false, false, false,
                                   false, false, false,
                                   false, false, false,
                                   false, false, false]</rosparam>

    <param name="odom0_differential" value="false"/>
    <param name="smooth_lagged_data" value="true"/>
  </node>

  
  <node pkg="robot_localization" type="navsat_transform_node"
        name="navsat_transform_node" respawn="true" output="screen">
         <param name="frequency" value="60"/>
    <param name="magnetic_declination_radians" value="0"/>
    <param name="broadcast_utm_transform" value="true"/>
    <param name="~zero_altitude" value="true"/>
    <param name="wait_for_datum" value="true"/>
    <param name="use_odometry_yaw" value="true"/>
    <rosparam param="datum">[21.30996, -157.8901]</rosparam>
    <param name="yaw_offset" value="0"/>
    <param name="publish_filtered_gps" value="true"/>
    <remap to="/sensors/gps/gps/fix" from="/robot_localization/gps/fix" />
  </node>
</launch>

**Comment by qycqycqyc** [comment]
![2020-07-11 20-32-29屏幕截图](https://user-images.githubusercontent.com/48520573/87224192-b6b47c80-c3b5-11ea-8863-28f24865b3fd.png)
![2020-07-11 20-32-47屏幕截图](https://user-images.githubusercontent.com/48520573/87224196-ba480380-c3b5-11ea-8321-ca001d205945.png)

**Comment by qycqycqyc** [comment]
![2020-07-11 20-32-29屏幕截图](https://user-images.githubusercontent.com/48520573/87224205-e3689400-c3b5-11ea-9368-29a492fa803b.png)

**Comment by qycqycqyc** [comment]
node pkg="robot_localization" type="ekf_localization_node"
        name="ekf_localization" clear_params="false"
 param name="sensor_timeout" value="2.0"/
param name="two_d_mode" value="false"/
param name="map_frame" value="map"/
param name="odom_frame" value="odom"
param name="base_link_frame" value="base_link"/
param name="world_frame" value="odom"/
param name="publish_tf" value="true"/
param name="~zero_altitude" value="true"/
param name="frequency" value="60"/
param name="imu0" value="/sensors/imu/imu/data"/




node pkg="robot_localization" type="navsat_transform_node"
        name="navsat_transform_node" respawn="true" output="screen">
         param name="frequency" value="60"/
    param name="magnetic_declination_radians" value="0"/
    param name="broadcast_utm_transform" value="true"/
    param name="~zero_altitude" value="true"/
    param name="wait_for_datum" value="true"/
    param name="use_odometry_yaw" value="true"/
    rosparam param="datum">[21.30996, -157.8901]</rosparam>
    param name="yaw_offset" value="0"/
    param name="publish_filtered_gps" value="true"/
