### ISSUE TITLE
Cannot start usv_keydrive.launch

### ISSUE THREAD

**Issue by dimosthenis8** [osrf/vrx#215]
I have installed the vrx_gazebo package following this tutorial https://github.com/osrf/vrx/wiki/tutorials-SystemSetupInstall . However when i try to use the Driving options by executing roslaunch vrx_gazebo usv_keydrive.launch i keep getting errors
**ERROR: cannot launch node of type [vrx_gazebo/key2thrust_angle.py]: Cannot locate node of type [key2thrust_angle.py] in package [vrx_gazebo]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [vrx_gazebo/twist2thrust.py]: Cannot locate node of type [twist2thrust.py] in package [vrx_gazebo]. Make sure file exists in package path and permission is set to executable (chmod +x)**
Any idea what should i do?

**Comment by mabelzhang** [comment]
The error messages mean that you should run this:
```
chmod +x key2thrust_angle.py
chmod +x twist2thrust.py
```
As for the location of the files, you can find them by running these in the workspace directory:
```
find . -name key2thrust_angle.py
find . -name twist2thrust.py
```

However, I will say that technically, the correct way is to run
```
catkin_make install
```
which will install those two scripts as executables (added recently in https://github.com/osrf/vrx/blame/master/vrx_gazebo/CMakeLists.txt#L311-L314 ), and you won't have to manually `chmod` or find the files. They should just work.
