### ISSUE TITLE
Missing vrx_gazebo files

### ISSUE THREAD

**Issue by ijulanday** [osrf/vrx#232]
Building the repository with catkin_make fails due to the following files not present in this repository:

- vrx_gazebo/Task.h
- vrx_gazebo/Contact.h

I was able to work around this by editing the vrx_gazebo/CMakeLists.txt so that it would not make the gui_task_widget node, but I would like to see these implemented.

**Comment by mabelzhang** [comment]
These files are compiled from the message files `Task.msg` and `Contact.msg`, which are in `vrx_gazebo/msg` https://github.com/osrf/vrx/tree/master/vrx_gazebo/msg

If you don't get them in the first compilation, you should be able to run catkin again, and it should find it.
