### ISSUE TITLE
Migrate generate_avoid_obstacles_buoys script to Python 3 for Noetic

### ISSUE THREAD

**Issue by bsb808** [osrf/vrx#242]
The generator script: 
https://github.com/osrf/vrx/blob/master/vrx_gazebo/scripts/generate_avoid_obstacles_buoys

Uses Python 2.  In https://github.com/osrf/vrx/pull/243 commented this out for Noetic.  This issue is to remind us to port to Python 3.

**Comment by M1chaelM** [comment]
This script is now ported and can be added back.

**Comment by bsb808** [comment]
closing for @M1chaelM
