### ISSUE TITLE
Which one is the melodic branch?

### ISSUE THREAD

**Issue by OhmySallyGarden** [osrf/vrx#245]
Is there anyone could tell me which one is the melodic branch? Thanks!

**Comment by caguero** [comment]
It should be `master`.

**Comment by OhmySallyGarden** [comment]
It's not.

**Comment by M1chaelM** [comment]
@OhmySallyGarden Technically, there is no "Melodic" branch. We have migrated to official support for Noetic. However, the platform should still run on Melodic. If you're encountering errors trying to get it to run, please create a new issue describing the error.
