### ISSUE TITLE
The color of the sea is not rendered

### ISSUE THREAD

**Issue by OhmySallyGarden** [osrf/vrx#246]
The color of the sea is not rendered， what's the problem?

**Comment by caguero** [comment]
Hi @OhmySallyGarden , do you satisfy the system requirements? https://github.com/osrf/vrx/wiki/system_requirements

**Comment by OhmySallyGarden** [comment]
I'm using VMworkstation to run vrx in ubuntu system, would it matters？Please see the command line.
![1](https://user-images.githubusercontent.com/37887274/124563121-58a86100-de72-11eb-94dd-346a5c36b5a2.PNG)

**Comment by caguero** [comment]
Unfortunately, it matters and that is not a supported environment. Please, try to use the recommended system.
