### ISSUE TITLE
WAMV missing from SandIsland Launch

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#257]
One of our recent pull requests has broken `sandisland.launch`. Attempting to launch it now loads the Sydney arena instead of Sand Island, and the WAM-V is missing:

![sandisland_wuzzled](https://user-images.githubusercontent.com/8611855/125129719-bf1cc180-e0b4-11eb-9d30-2b606df81832.png)

Although Sand Island is no longer strictly needed for VRX 2022, it would be nice to still be able to use it for basic demos and tutorials involving the VRX platform.

**Comment by M1chaelM** [comment]
@caguero Could you take a look at this?

**Comment by crvogt** [comment]
@M1chaelM It looks more like a GPS issue, the WAM-V is there, just not at the camera location at the start. I can set it up with the WAM-V in the correct location, unless you'd rather revert to the sandisland map.

**Comment by M1chaelM** [comment]
@crvogt Thanks--yes, I think changing the environment that the `sandisland.launch` file pulls up is probably an unintended consequence of recent changes (and maybe a problem with the way the launch file was originally written). It should continue to bring up Sand Island (Honolulu).

**Comment by caguero** [comment]
This issue should be fixed in https://github.com/osrf/vrx/pull/256. I forgot to update a launch file.

**Comment by M1chaelM** [comment]
Confirming this is now fixed. Thanks!
