### ISSUE TITLE
Update to Python files to use Python3

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#261]
## Context
* Since we are moving to Ubuntu 20.04, python 2 is no longer installed by default.
* We could install it, but this adds dependencies and some amount of confusion keeping the versions straight.
* We only have about a dozen python files and it is not too hard to move them to python 3 (in many cases this is just a matter of changing outdated executable paths at the top of the script).

## Proposed
Let's make our code work with Python 3.

**Comment by crvogt** [comment]
@M1chaelM This seems like something I can take care of.

**Comment by M1chaelM** [comment]
It looks like our acoustic pinger tutorial may rely on this changes, since the `pinger.launch` file fails with the Python error:
```
ImportError: No module named yaml
```
This comes from both the `pinger_visualisation.py` and `set_pinger_position.py` nodes. The yaml module is definitely installed so I think these are trying to run python 2.

**Comment by crvogt** [comment]
@M1chaelM I found that by simply modifying the shebangs at the top of the python files to python3 the pinger tutorial work fine. I haven't tested in Melodic though. I think ideally there'd be a parameter to use one or the other, but for a quick fix, this does work. Thoughts?

**Comment by M1chaelM** [comment]
I think changing to force running in Python 3 should be fine. This will just mean that people running in Melodic need to install Python 3, which shouldn't be too much of a burden. It looks like @caguero did find a couple places where the code needs to be updated to eliminate things that aren't supported in Python 3, so it may be worth skimming through to look for these in case they don't pop up right away in testing.

**Comment by crvogt** [comment]
@M1chaelM Sounds good!

**Comment by M1chaelM** [comment]
Fixed in PR #265 and #266.
