### ISSUE TITLE
New Tutorial: Control Thruster Articulation with Gamepad

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#262]
Our [thruster articulation tutorial](https://github.com/osrf/vrx/wiki/tutorials-thruster_articulation) says we can control thruster angle with a gamepad using usv_joydrive.launch but we do not explain what the controls are. If the user needs to do something to configure these we should say this and, if possible, say how to do it.

**Comment by bsb808** [comment]
Should be addressed with PR#308
