### ISSUE TITLE
Implement the deliver aspect of the "Dock and deliver" task

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#280]
* Model a basic launcher (it could be as simple as a cylinder. We can potentially have Cole to model something that looks nicer).
* Write a plugin that let the teams to throw a projectile.
  * Define the API: It could go from exposing some velocity control at the end of the launcher and optionally to add pan/tilt capabilities. We should ask Arjo about the common API in RobotX. Not sure if it's common to control pan/tilt in this actuator. 
  * Implement the functionality in the plugin

**Comment by M1chaelM** [comment]
This issue was resolved with #311 and #316.
