### ISSUE TITLE
Verify scoring plugins of tasks 1, 2, 3 and 5

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#281]
Test these tasks with the scoring plugins running and verify that the scores match what we describe in the 2022 "VRX Competition and Task Description" document.

**Comment by M1chaelM** [comment]
This task depends on the prior completion of the following tasks:
* #272
* #273
* #274
* #277

**Comment by M1chaelM** [comment]
Slightly redundant with #293. The intent of this issue was just to check that scoring is working for tasks where the scoring plugin had already been developed (the omitted tasks are the ones that we made new scoring plugins for this time).

**Comment by j-herman** [comment]
I am working on task 1 for both the scoring plugin and tutorial verification
