### ISSUE TITLE
Test all the tutorials

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#293]
Use this ticket to organize who is testing each tutorial.

**Comment by M1chaelM** [comment]
Following [this testing plan](https://docs.google.com/spreadsheets/d/1s60ptIg2Dau96Y_Z0M9AvalAJawofmDaGbQI9WT1QZY/edit#gid=0).

**Comment by j-herman** [comment]
I am working on task 1 for both the scoring plugin and tutorial verification
