### ISSUE TITLE
about driving using rostopic pub (/wamv/thrusters/left_thrust_cmd & /wamv/thrusters/right_thrust_cmd) 

### ISSUE THREAD

**Issue by boeun98** [osrf/vrx#296]
Hi, I'm trying to drive using 'rostopic pub' and make a new node.

I succeeded in driving by creating a new node.

But, I want to run this for a certain time.

I want to add 'time' to '/wamv/thrusters/left_thrust_cmd'    and     '/wamv/thrusters/right_thrust_cmd' topics.
What should I do?

**Comment by caguero** [comment]
If I understand correctly, what you're trying to do is to create a navigation controller piece of code that periodically sends thruster commands. If that assumption is correct, you need to write a dedicated piece of code that is executed periodically using a loop or some kind of callback that is called periodically. Then, inside that piece of code you'll need to figure out the commands to send, and then, publish the message thrusters.
