### ISSUE TITLE
Create individual tutorial infrastructure for each 2022 task

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#299]

**Comment by M1chaelM** [comment]
The tutorial templates are now at the following links:
1. https://github.com/osrf/vrx/wiki/vrx_2022-station_keeping_task
1. https://github.com/osrf/vrx/wiki/vrx_2022-wayfinding_task
1. https://github.com/osrf/vrx/wiki/vrx_2022-perception_task
1. https://github.com/osrf/vrx/wiki/vrx_2022-wildlife_task
1. https://github.com/osrf/vrx/wiki/vrx_2022-gymkhana_task
1. https://github.com/osrf/vrx/wiki/vrx_2022-scan_dock_deliver_task

These have been added to the relevant tasks.
