### ISSUE TITLE
GPS coordinate mismatch

### ISSUE THREAD

**Issue by crvogt** [osrf/vrx#312]
EDIT: "Fixed". Need to uncomment `<heading_deg>180</heading_deg>` AND change `<referenceHeading>` field to 270 in `wamv_gps.xacro`.

The position of the WAM-V in simulation doesn't match map lat/lon.

Modified `wamv_gps.xacro` with world origin lat/lon

Changing the `<referenceHeading>` field in `wamv_gazebo.xacro` seems to have a corrective effect in terms of direction, but the length scale is wrong.

Changing parameters in the `sydneyregatta.xacro` `<spherical_coordinates>` field hasn't had an effect for me.

WAM-V starting position via Google Maps
![Screenshot from 2021-08-12 15-19-39](https://user-images.githubusercontent.com/8268930/129280492-4ebae442-d842-4edb-9731-18469de9d6a2.png)
World Origin via Google Maps
![Screenshot from 2021-08-12 15-19-27](https://user-images.githubusercontent.com/8268930/129280483-3efb0fe8-8327-4fcb-b855-32f79a9cd080.png)
WAM-V starting position in Gazebo
![Screenshot from 2021-08-12 15-48-00](https://user-images.githubusercontent.com/8268930/129280507-906d6ffb-0e9d-4e70-9c4a-70e63d4aa41d.png)
WAM-V at origin in Gazebo
![Screenshot from 2021-08-12 15-48-59](https://user-images.githubusercontent.com/8268930/129280514-8cc24974-ceed-45b6-b449-051a48ad5b3f.png)

**Comment by crvogt** [comment]
Setting the `<referenceHeading>` field in `wamv_gps.xacro` to 270 puts the WAM-V at the correct position. Will now check that placing buoys workds in the world via lat/lon

**Comment by M1chaelM** [comment]
This was resolved with #313
