### ISSUE TITLE
Is the Sydney Regatta map orientation correct?

### ISSUE THREAD

**Issue by bsb808** [osrf/vrx#353]
I may be confused, but I think the Sydney Regatta map is incorrectly oriented.  

I launch the regatta world with the USV at the origin...

```
roslaunch vrx_gazebo sydneyregatta.launch x:=0 y:=0 Y:=0
```

Here is what I believe is the birds eye view of the location with North up.
![Screenshot from 2021-09-10 11-03-52](https://user-images.githubusercontent.com/8921143/132898258-9ce26e00-746d-470b-b31e-ba19ecbc40e4.png)

And here is the google map view...
![Screenshot from 2021-09-10 11-05-04](https://user-images.githubusercontent.com/8921143/132898283-fa7fe2ef-14f6-48fb-8a5d-e9863588b377.png)

Are we 180 degrees off?  

Is this as simple as applying a Yaw rotation to the model origin?

**Comment by M1chaelM** [comment]
Uh oh, I wonder if this is related to:
* #312 

@crvogt noticed last month that the GPS coordinates were reversed. The PR is not referenced in the issue, but I will look for it to see whether this is a side effect of our solution.

**Comment by M1chaelM** [comment]
Update: #312 was resolved with:
* #313
Which rotated the arena 180 degrees in this commit: https://github.com/osrf/vrx/pull/313/commits/b574656fe9a2e4f6ab6e3f99485e83a6f095c950

I could be misunderstanding, but it seems like this fix had the unintended consequence you are noticing here.

**Comment by bsb808** [comment]
> Update: #312 was resolved with:
> 
> * [Update Station Keeping Task #313](https://github.com/osrf/vrx/pull/313)
>   Which rotated the arena 180 degrees in this commit: [b574656](https://github.com/osrf/vrx/commit/b574656fe9a2e4f6ab6e3f99485e83a6f095c950)
> 
> I could be misunderstanding, but it seems like this fix had the unintended consequence you are noticing here.

The first thing to make sure we have correct is the Gazebo coordinates (ENU) and how they relate to the Sydney map.  The spherical_coordinates parameters should be independent of this .  I don't believe that changing the <heading_deg> parameter will affect the gazebo coordinate orientation.

**Comment by caguero** [comment]
I see a 180 deg. rotation applied in the world [here](https://github.com/osrf/vrx/blob/master/vrx_gazebo/worlds/sydneyregatta.xacro#L41).

**Comment by caguero** [comment]
I think you're right about this. I believe we need to undo the yaw rotation for the SydneyRegatta model in the world. [Here](https://github.com/osrf/vrx/blob/master/vrx_gazebo/worlds/sydneyregatta.xacro#L41).

Then, assuming that our GPS coordinates are working correctly right now, I guess, we'll need to undo the `<heading_deg>180</heading_deg>` in the `<spherical_coordinates>` section, right? [Here](https://github.com/osrf/vrx/blob/master/vrx_gazebo/worlds/sydneyregatta.xacro#L22).

**Comment by bsb808** [comment]
I'm hoping that the two things - the geodetic-mapping and the orientation of the model - are independent.  Trying now.
