### ISSUE TITLE
Make it easier to specify waypoints for wildlife

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#363]
## Current State
The waypoints that the animals travel between are currently hard coded in the sdf and are given in global rectangular coordinates. This means if you want to change the starting location of a wildlife buoy you need to also change the coordinates of the waypoints in the model.sdf so they make sense for that start point. The user needs to calculate what "makes sense" on their own.

## Desired State
To make it easier to move models around, it would be nice if they didn't have to be coded into the model and the user was provided some kind of help determining what they should be. One way to do this would be to specify the waypoints relative to the starting position. There may also be other, better solutions.

**Comment by j-herman** [comment]
I have a working version that allows you to specify relative motion in a line or in a circle via tags in the model.sdf - so we could have a North-South turtle, an East-West turtle, etc.  This is still a bit of a hack, but easier than having to modify the parameters each time.  Can put in a pull request if desired, or work on a better solution via xacro...?
There is new capability in SDF 1.7 that looks like it would make this much easier if/ when we want to move to that standard.
