### ISSUE TITLE
Registration Link Is Not Working

### ISSUE THREAD

**Issue by MustafaBayrak1** [osrf/vrx#381]
Hello everyone! It seems like https://robotx.org/programs/vrx-competition-2022/ page is updated and a registration link is added. However, it's not working properly. Pardon me if here is not the proper place to report a competition related issue and not a code related thing but here it goes.
![image](https://user-images.githubusercontent.com/43607777/137640107-89047c6e-ceef-4b84-a4df-6e9f6fbbc136.png)

**Comment by bsb808** [comment]
Hi @MustafaBayrak1 -  Unfortunately, we do not have access to the RobotX web interface.  I'll send a not to the RoboNation folks, but I recommend posting your issue to the RoboNation forum: https://robonationforum.vbulletin.net/forum/robotx/-2022-virtual-robotx-competition
