### ISSUE TITLE
Wiki Update: sand_island_tutorial

### ISSUE THREAD

**Issue by Tinker-Twins** [osrf/vrx#393]
[Run instructions](https://github.com/osrf/vrx/wiki/sand_island_tutorial#run-instructions) of the `sand_island_tutorial` seem outdated. Paticularly, the launch command to run the Sand Island example needs to be updated since the `sandisland.launch` file is no longer in the `vrx_gazebo` package, but instead in the `vrx_2019` package. The correct launch command (according to the updated repository structure) should therefore be as follows:
```bash
$ roslaunch vrx_2019 sandisland.launch
```

**Comment by caguero** [comment]
Thanks, I just updated the tutorial.
