### ISSUE TITLE
No tf_tree

### ISSUE THREAD

**Issue by JTDeve** [osrf/vrx#401]
Hi,My environment is Ubuntu18 and Melodic ,I use tag 1.3.0
when i roslaunch vrx_gazebo vrx.launch,then rosrun rqt_tf_tree rqt_tf_tree show no tf data

**Comment by caguero** [comment]
Hi, the `tf` tree is published when you launch:

```
roslaunch wamv_gazebo rviz_vrx.launch
```

**Comment by JTDeve** [comment]
@caguero It works,Thank you !!!
