### ISSUE TITLE
Make example worlds exactly match the generated files

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#403]
We now have yaml files in vrx-docker that create practice worlds that are equivalent to the hand-generated versions stored in the 2022_practice directory in vrx, but look a little different because of the way they are generated. Let's make them identical to avoid any confusion.

**Comment by M1chaelM** [comment]
@caguero and @crvogt Could you review the plan above and make sure I'm not eliminating something we need?

**Comment by M1chaelM** [comment]
Apologies, I forgot we updated the component_config.yaml for both example teams in https://github.com/osrf/vrx-docker/pull/42. The updated examples are different enough that it seems to justify having two of them.

**Comment by M1chaelM** [comment]
On further reflection, I don't think we need to cache the generated worlds in the vrx-docker repository since they are already in the vrx repository. So I will just update the vrx_2022 versions so they are exact matches.

**Comment by caguero** [comment]
See #404 .
