### ISSUE TITLE
Minor bug in wamv_p3d.xacro

### ISSUE THREAD

**Issue by adthoms** [osrf/vrx#407]
in `vrx/wamv_gazebo/urdf/components/wamv_p3d.xacro`, line 7 should read:

```
<bodyName>wamv/base_link</bodyName>
```
instead of 

```
<bodyName>base_link</bodyName>
```

when using this sensor with `vrx/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro`, the following error is thrown:

```
[FATAL] [1637703004.599982711, 0.001000000]: gazebo_ros_p3d plugin error: bodyName: base_link does not exist
```

**Comment by caguero** [comment]
See #408 .
