### ISSUE TITLE
Documentation Update: Sensor Placement

### ISSUE THREAD

**Issue by Tinker-Twins** [osrf/vrx#410]
Section 4.4 of the [Tecnical Guide](https://robonation.org/app/uploads/sites/2/2021/09/VirtualRobotX2022_Technical-Guide_v1.0.pdf) elucidates the Sensor Placement (page 5) wherein the document depicts an image representing the allowed sensor regions in WAM-V. While this gives a general idea of the allowed sensor placement regions, it would be much better to incude a table describing the exact `Center` and `Size` of the bounding boxes (as in case of the thruster configuration).

The following table has been generated based on the component compliance bounding boxes [yaml file](https://github.com/osrf/vrx/blob/master/vrx_gazebo/config/wamv_config/component_compliance/bounding_boxes.yaml). It hosts the `Center` and `Size` parameters for the sensor configuration bounding boxes. The same have been verified in Gazebo.

| Placement Region | Bounding Box Center (x y z R P Y) | Bounding Box Size (x y z) |
| -------------------- | ------------------------------------- | ---------------------------- |
| Front                      | 0.8 0 1.8 0 0 0                                 | 1 1 1                                 |
| Back                       | -0.9 0 1.8 0 0 0                               | 0.5 1 1                               |

It is requested to include this table in the documentation in order to aid the novice developers quickly configure their WAM-V without needing to search these parameters through the source files.

**Comment by caguero** [comment]
Thanks for the suggestion! I've included a similar table in the 1.1 revision. It'll be available to download soon.
