### ISSUE TITLE
Outdated wiki: changing_plugin_params_tutorial

### ISSUE THREAD

**Issue by AntonBock** [osrf/vrx#413]
Hello

I am trying to add fog to my scene. According to [this tutorial](https://github.com/osrf/vrx/wiki/changing_plugin_params_tutorial), the file location for changing fog parameters is in `vrx_gazebo/worlds/sandisland.xacro`. However, i cannot find this file. 

I don't know if I am missing something super obvious, or if a file location has changed since the last update of the wiki. Hope someone can help!

Best regards, 
Anton

**Comment by AntonBock** [comment]
If anyone can point me in the correct direction of adding fog to a scene, that would be wonderful as well

**Comment by M1chaelM** [comment]
You're right--thanks for pointing this out. I've updated the tutorial. The `sandisland.xacro` file has been moved to the `vrx_2019` package. The VRX 2022 environment uses `sydneyregatta.xacro` instead, so if you are working on VRX 2022 that is the one you want.

**Comment by AntonBock** [comment]
No problem, thanks! 

Can you elaborate on how specifically the fog is added? I have been through the documentation and the referenced files, and cannot figure it out.

**Comment by M1chaelM** [comment]
Sure. I've made some additional updates to the tutorial to try to clarify the process: https://github.com/osrf/vrx/wiki/changing_visual_params_tutorial 

Could you check whether this resolves the problem for you? If not, it would be helpful to know what you've tried and what the results are.

**Comment by AntonBock** [comment]
Thank you! I was missing the `type` tag, adding this fixed it.
