### ISSUE TITLE
Sandisland Test does not link to the correct launch file path

### ISSUE THREAD

**Issue by alexperez33** [osrf/vrx#418]
Within the ```vrx_gazebo``` package, there is a test that is failing because it cannot find the appropriate launch file. The path provided within this test leads to ```$(find vrx_gazebo)/launch/sandisland.launch```. This real location of this launch file has been moved to the ```vrx_2019/launch``` directory.

I am unsure if we would want to link it to the proper file path, or whether the test should be removed from the CMakeLists.txt since sandisland.launch was moved to the vrx_2019 directory.

**Comment by caguero** [comment]
Thanks for reporting it. See pull request #422

**Comment by caguero** [comment]
Fixed in #422 .
