### ISSUE TITLE
Wildlife Encounter and Avoid Task does not provide correct spherical coordinates

### ISSUE THREAD

**Issue by alexperez33** [osrf/vrx#420]
It appears the spherical coordinates provided by the wildlife encounter and avoid task topic ```/vrx/wildlife/animals/poses``` do not correspond with the locations of the actual animals. After some investigation, it appears that the poses provided in the ```wildlife_task.world.xacro``` file seem correct. But when converted to spherical coordinates in the ```SphericalFromLocal``` function within the ```wildlife_scoring_plugin.cc```, the poses no longer seem to correspond to that of the animals.

One way of showing this is by typing in the topic's latitude and longitude into this website: https://www.latlong.net/lat-long-utm.html. Moreover, when converting the provided latitude and longitude to a pose in reference to enu, I am provided with a pose that corresponds to that of the website above, not the actual animals.

Please let me know if I am missing something.

**Comment by j-herman** [comment]
Closing this issue based on merge of https://github.com/osrf/vrx/pull/428.  The topic is now publishing the correct lat/ long.
