### ISSUE TITLE
Yaml Component Generation does not allow pinger placement

### ISSUE THREAD

**Issue by alexperez33** [osrf/vrx#423]
Within ```wamv_gazebo.urdf.xacro``` there is an if statement that suggests if the ```yaml_component_generation``` arg is true, it will look at the user's component xacro file generated during compilation. Due to this, if you choose to use a component xacro file, you will have to decide the locations of the GPS, imu, lidar, cameras, P3D, ball shooter, and pinger (otherwise these sensors are not instantiated).

This is all fine, however, the issue comes when you try to put the pinger in the ```component_config.yaml```, it complains that ```wamv_pinger``` is not defined in ```vrx_gazebo/config/wamv_config/component_compliance/numeric.yaml```. It seems that this file defines what links and parameters you are allowed to edit in your ```component_config.yaml```.

**Comment by caguero** [comment]
See #424 .
