### ISSUE TITLE
Adding Radar Capabilities to the WAM-V

### ISSUE THREAD

**Issue by francescofraternali** [osrf/vrx#425]
Is it possible to add a radar to the current WAM-V system? It will be very useful to enhance the current capabilities of the simulator. Thank you very much in advance for your work and help, I really appreciate it.

**Comment by caguero** [comment]
Hi @francescofraternali . I agree that it would be a great addition but unfortunately is out of the scope of the project for now. We have never implemented a radar sensor in Gazebo or Ignition and I suspect isn't a trivial sensor. Please, feel free to add extra information if you know an existing open source implementation.
