### ISSUE TITLE
Support for a single thruster and a rudder

### ISSUE THREAD

**Issue by Fran-FC** [osrf/vrx#434]
Hello, I am trying to implement a boat simulation with a single thruster and a rudder, I was wondering if it is possible to do it using this repo. As for what I've seen for now, the boat included in the repo uses two thrusters for the navigation.

**Comment by bsb808** [comment]
@Fran-FC 
We don't have a platform in VRX that has fixed propeller and rudder.  Our main use-case is supporting the RobotX competition which uses a common platform with differential thrust.  There are many other parts of VRX that can be used, but you'd need either find or build a platform with the propulsion model you are considering.

You might look at the work by @srmainwaring  - they have done some really cool work in the space and made important contributions to VRX.  They might have a robot model that would work for you: https://github.com/srmainwaring

This project has some models that might be comparable - but it looks like project hasn't been active in awhile: https://github.com/disaster-robotics-proalertas/usv_sim_lsa

**Comment by Fran-FC** [comment]
Thank you for your reply! I saw the usv_sim_lsa repo but it is broken and unmaintained, I will try to implement myself the controller for the platform and include it in the vrx world

**Comment by mzahana** [comment]
Hi @Fran-FC !
I am planning to simulate a tugboat with a single engine, similar to what you mentioned. Are you able to implement the required model(s)?
