### ISSUE TITLE
Gymkhana 2022 practice worlds give different positions for stationkeeping and acoustic pinger plugins

### ISSUE THREAD

**Issue by alexperez33** [osrf/vrx#437]
It seems that the world files for the gymkhana task give the stationkeeping plugin certain coordinates. However, the acoustic pinger plugin reads from a file called pinger.yaml to obtain certain coordinates that the acoustic pinger plugin converts to range, bearing, and elevation. While in the gymkhana.world.xacro file, the stationkeeping plugin goal coordinate corresponds with the value in the pinger.yaml file, in the rest of gymkhana practice tasks, the stationkeeping plugin goal coordinate is not the same as the value in the pinger.yaml file.

Essentially, for the 2022_practice tasks, it seems that the wrong coordinate is converted to range, bearing, and elevation values which causes the boat to go to a different coordinate than the stationkeeping plugin is asking for (because it is obtaining the "goal" from the pinger.yaml file).

**Comment by caguero** [comment]
@alexperez33 , thanks for reporting this issue. Indeed, this seems like a bug. Could you verify the patch in #438 ?

**Comment by alexperez33** [comment]
I made a suggestion in #439, thanks for the quick fix!
