### ISSUE TITLE
Placard subscriber seems to sometimes instantiate after new dock symbols are published

### ISSUE THREAD

**Issue by alexperez33** [osrf/vrx#451]
This issue pertains to the Scan Dock and Deliver task.

I was not able to replicate this issue using only the vrx related launch files. However, when I launch my code alongside the vrx code, I noticed that sometimes the publisher within ```scan_dock_scoring_plugin.cc``` within the AnnounceSymbol function publishes the dock symbols before the subscriber within ```placard_plugin.cc``` is even instantiated. This is not always the case, but when it is the case, the dock simply ends up showing the default "blue_circle" symbols because the subscriber never receives the actual symbols published from  ```scan_dock_scoring_plugin.cc```. (The dock symbols are only published once).

I am not sure exactly why it takes so long for the subscriber in ```placard_plugin.cc``` to instantiate. Perhaps there is a lot of other code that is starting up simultaneously which could cause this delay. Regardless, I believe the solution for this would be to make the gazebo subscriber within ```placard_plugin.cc``` allow latching. This way once even if the msgs are published before the subscriber is instantiated, the subscriber can still just get the last published message.

**Comment by M1chaelM** [comment]
Resolved with #452
