### ISSUE TITLE
Tugboat simulation

### ISSUE THREAD

**Issue by mzahana** [osrf/vrx#476]
Hi!

Thanks a lot for this great project!

I am trying to simulate a tugboat in Gazebo  and found this project a great place to start.

Assuming that I have the urdf model of the tugboat with a single engine, I would like to know what needs to be modified in terms of plugins in order to have a good enough simulation in Gazebo with the Gazebo worlds provided in this repo.

Thanks.

**Comment by M1chaelM** [comment]
Hi @mzahana .

Unfortunately, we don't yet have a step-by-step guide for customizing the physics of a new platform, but you might start by looking at this tutorial: https://github.com/osrf/vrx/wiki/changing_plugin_params_tutorial

Depending on what kind of fidelity you're looking for, you may want to customize plugins for hydrodynamics, thrusters and wind. It might also be helpful to refer to our paper, [Toward Maritime Robotic Simulation in Gazebo](https://wiki.nps.edu/display/BB/Publications?preview=/1173263776/1173263778/PID6131719.pdf). The section on the vehicle model explains the approach we've taken with the WAMV.

Hope that helps!
