### ISSUE TITLE
how to use the gps as  nothing in topic wamv/sensor/gps/gps/fix

### ISSUE THREAD

**Issue by SSROMEE** [osrf/vrx#499]

**Comment by M1chaelM** [comment]
Hi! Could you please add an issue description? It would be helpful to include:
* Your system setup (OS, hardware, ros and gazebo version)
* What commands you're running.
* The behavior you expect.
* The behavior you're observing (including any relevant output or error messages).

If this issue relates to documentation please include a link to any relevant tutorials or pages on our [Wiki](https://github.com/osrf/vrx/wiki). Thanks!
