### ISSUE TITLE
Gazebo always end in 5:19 

### ISSUE THREAD

**Issue by SSROMEE** [osrf/vrx#521]
this puzzled me for long, hop the author can help me 
![1664435623(1)](https://user-images.githubusercontent.com/98152870/192965759-84c1cc36-cae3-4f60-8a65-9270e951e07f.png)

**Comment by M1chaelM** [comment]
A first guess is that you may be running a competition scoring plugin, which times out and terminates the simulation. Are you running one of the launch files associated with a competition task, or a file that you created based on one of those files?

If the above seems unlikely, please post the instructions for reproducing this situation.

**Comment by M1chaelM** [comment]
Closing for now. Feel free to re-open if the issue persists.
