### ISSUE TITLE
Autonomous driving using Wam-v's camera

### ISSUE THREAD

**Issue by mazik1496** [osrf/vrx#533]
hello. I have a question, so I'm posting it here.
I would like to implement an autonomous driving code that bypasses the object in front when it recognizes an object in front using the camera of wam-v in the ROS gazebo.
However, in the case of open source code, there is no autonomous driving code, so I would like to ask if it is possible to implement autonomous driving code with wam-v's camera. And I would like to ask which example should I refer to to implement this.

**Comment by caguero** [comment]
Sorry but this is an unrelated VRX issue.
