### ISSUE TITLE
Gymkhana Plugin does not register collisions

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#546]
Collisions were added in #502 but don't seem to be showing up during the gymkhana task for some reason.

**Comment by caguero** [comment]
#547 should fix it. For some reason this [instruction](https://github.com/osrf/vrx/pull/504/files#diff-b72325551bead843ffdc7af5741a423673774b4e3db164a5721693d4f3a6fbceR411-R412) was removed.

**Comment by M1chaelM** [comment]
Yes, this seems to be counting collisions now! Thanks.
