### ISSUE TITLE
How can I get the odom message?

### ISSUE THREAD

**Issue by woshiganfanren** [osrf/vrx#556]
i find there is no odom message . how can i  add it ?  thanks

**Comment by bsb808** [comment]
Robotic surface vessels are a bit different from land-based examples in that there is not direct analog to an "odometry" sensor such as wheel encoders.  Therefore, there are a variety of localizations solution that will generate an 'odom' message.     

A couple of options include...
* Fuse the simulated GPS and IMU data to provide a localization solution.  There are some ROS projects that can be used to support - e.g., fuse and robot-localization.
* Simulate an GPS-aided IMU sensor that does this fusion onboard, e.g., https://www.microstrain.com/inertial-sensors/3dm-gx5-45

Alternatively, if you are interested in a ground truth Odometry message, you might consider using the P3D plugin - https://classic.gazebosim.org/tutorials?tut=ros_gzplugins
