### ISSUE TITLE
Wavefield parameters are set in too many places

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#564]
In our Gazebo Sim implementation, wavefield values must be specified separately for every instance PolyhedraBuoyancyDrag plugin, which must be attached to every buoyant object. Conceptually, this is bad because there is only one actual wavefield per body of water, and we never want to specify different wavefield values for different objects floating in the same body of water. Practically, it's bad because it means we have to manually keep all these values in sync, or use a script like the one introduced in PR #557 .

To fix the conceptual problem, we would ideally only have a single wave field associated with a body of water, and have our buoyancy plugin somehow access it. I'm not sure whether this is feasible right now.

A compromise we've used in the past is to use xacro variables to generate sdfs with appropriately synchronized values at build time. This has not been ported to GazeboSim and there may now be better tools for doing this in a clean way (e.g., maybe using embedded ruby or yaml would help clean this up?).

**Comment by caguero** [comment]
It should be possible to agree on a canonical wave plugin and only specify SDF parameters in there. This plugin, after parsing the SDF params, should create a new wavefield component in the ECM. Then, all the other plugins that need wave parameters shouldn't have to parse any SDF. Instead, they should read from the ECM the wavefield component and initialize it accordingly. 

It's relevant to consider the following observations:

* The ECM in the server synchronizes with the ECM in the client but not viceversa. This limitation forces us to not make the visual plugin the canonical one, as other plugins running in the server wouldn't be able to access the wavefield component.
* If we agree on a certain plugin as the canonical one, we might have the issue of having multiple instances of that plugin running. We might have to check if a wavefield component has already been created before creating a new one.
