### ISSUE TITLE
PYTHONPATH environment variable gazebo ws

### ISSUE THREAD

**Issue by atticusrussell** [osrf/vrx#581]
reading this [this page of the wiki](https://github.com/osrf/vrx/wiki/2023-running_vrx),  I see:
```
export PYTHONPATH=$PYTHONPATH:<YOUR_GAZEBO_WS>/install/lib/python
```
with the example 
```
export PYTHONPATH=$PYTHONPATH:/home/caguero/garden_ws/install/lib/python
```

in the [previous page of the wiki](https://github.com/osrf/vrx/wiki/2023-installation#installation-from-source), it lists gazebo garden as a pre-requisite, and shows ~/vrx_ws/ as the name to install vrx stuff to.

does ```<YOUR_GAZEBO_WS> ``` mean that I need to install gazebo from source and build it in a workspace, instead of as a package, which is what I did?

I can't find ```install/lib/python``` inside of ```vrx_ws```

Sorry for the very basic question

**Comment by caguero** [comment]
You need to set `PYTHONPATH` pointing to the directory where you installed Gazebo Garden (not your VRX workspace). If you installed Gazebo garden from source, it should be as the tutorial says. If you installed Gazebo Garden from binaries, you shouldn't need to do anything.
