### ISSUE TITLE
Recognizing objects using adaptive thresholding or Canny edge detection

### ISSUE THREAD

**Issue by mazik1496** [osrf/vrx#599]
![스크린샷, 2023-03-03 21-37-17](https://user-images.githubusercontent.com/80936392/222722686-9b3e00db-35ef-4021-9a8f-11d828efb493.png)

I am doing object recognition using adaptive thresholding or Canny edge detection. Both work without problems, but in the case of adaptive binarization, a lot of noise occurs, and in the case of Canny edge, when received in real time, the edge line is disconnected. I want to do object recognition (buoy, tree, etc.) neatly using these two methods. Can you give me some advice on how to do it neatly?

**Comment by M1chaelM** [comment]
Hi! Thanks for using VRX. Generally speaking, this issue tracker is for reporting bugs or requesting features for the VRX environment code or documentation. For advice about solving autonomy problems in simulation, you may want to try posting on the [Gazebo Community forum](https://community.gazebosim.org/). For suggestions specifically about these two computer vision techniques, you might also try asking on the [opencv forum](https://forum.opencv.org/). 

Unofficially, in my personal opinion: it's very challenging to get robust object recognition working with these techniques!
