### ISSUE TITLE
How do i get VRX to run with ros2 foxy and ubuntu 20.04

### ISSUE THREAD

**Issue by eeeeryaaaan** [osrf/vrx#601]
Having issues running building VRX with ros2 foxy and ubuntu is there a fix to this?

**Comment by M1chaelM** [comment]
Unfortunately, we don't offer official support for this configuration. The current version of VRX [requires Ubuntu 22 and ROS 2 Humble](https://github.com/osrf/vrx/wiki/2023-installation). That said, it might be worth double checking that you've sourced your environment.
