### ISSUE TITLE
buoys, turtle, etc scaling

### ISSUE THREAD

**Issue by mazik1496** [osrf/vrx#612]
The VRX Environment has various elements such as buoys, turtles and crocodiles. But the question here is, can I customize the size of these elements so that I can resize them?

**Comment by M1chaelM** [comment]
Hi! This seems to be a general question about working with models in Gazebo. If you're not finding an answer in the Gazebo documentation, consider posting it to answers.gazebosim.org. If you have a question that is specific to the VRX Environment, you can re-open this issue or create a new one. Thanks!
