### ISSUE TITLE
The current coordinates of cora and wamv in marina.world and sandisland are reading strangely.

### ISSUE THREAD

**Issue by mazik1496** [osrf/vrx#613]
![image](https://user-images.githubusercontent.com/80936392/229146089-367b49c7-29ea-4dbe-af0b-11516c474edb.png)
![image](https://user-images.githubusercontent.com/80936392/229146168-18230ebd-796a-4c3e-9a6f-78feb8ee2aaa.png)

As you can see, the values of cora and wamv read from gazebo and the coordinates of cora and wamv by importing GetModelState from Python were found to be different. What could be the cause for this?

**Comment by caguero** [comment]
Hi, could you share the Python code that you're using?

**Comment by caguero** [comment]
Please, reopen if needed with the extra information. Thanks
