### ISSUE TITLE
ros2 launch vrx_gz sydney_regatta not working

### ISSUE THREAD

**Issue by gigiucles** [osrf/vrx#621]
I've installed the repo and all of the dependencies by following the wiki tutorial.  I feel like there is an issue finding the packages because I am getting this error when trying to launch the command, 
ros2 launch vrx_gz competition.launch.py world:=sydney_regatta
the error:
Package 'vrx_gz' not found: "package 'vrx_gz' not found, searching: ['/opt/ros/humble']"

**Comment by salgado** [comment]
inside the `~/vrx_ws `try: 
`source install/setup.bash`

**Comment by SuedaSen** [comment]
Same issue for me as well.

**Comment by caguero** [comment]
Please, reopen if still not working.
