### ISSUE TITLE
Wiki Tutorials for VRX 2023

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#631]
We need to add or update many tutorials on the Wiki, both to address changes due to the port to Gazebo Sim and to prepare for the VRX 2023 competition. This issue will help keep track of what tutorials are needed and what has been done so far. The list below is in progress.

Jessica:
* [x] VRX 2023 Competition Task Tutorial Overview, similar to the [task overview page from VRX 2022](https://github.com/osrf/vrx/wiki/vrx_2022-task_tutorials)
* [x] Updated Stationkeeping Tutorial (see the [VRX 2022 Stationkeeping Tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-station_keeping_task)--but note there shouldn't be an underscore in stationkeeping!)
* [x] Updated Wayfinding Tutorial (see the  [VRX 2022 Wayfinding Tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-wayfinding_task))
* [x] Updated Perception Tutorial (see the [VRX 2022 Perception Tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-perception_task))
* [x] New Acoustic Perception Tutorial ([link](https://github.com/osrf/vrx/wiki/vrx_2023-acoustic_perception_task))
* [x] Updated Wildlife Tutorial (see the [VRX 2022 Wildlife Tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-wildlife_task))
* [x] New Follow the Path Tutorial ([link](https://github.com/osrf/vrx/wiki/vrx_2023-follow_the_path_task))
* [x] New Acoustic Tracking Tutorial ([link](https://github.com/osrf/vrx/wiki/vrx_2023-acoustic_tracking_task))
* [x] Updated Scan, Dock and Deliver Tutorial (see the [VRX 2022 Scan Dock and Deliver Tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-scan_dock_deliver_task))

Michael:
* [x] Update Main Wiki page to feature VRX 2.0 and VRX 2023 Competition.
* [x] Create tutorial sequences
* [x] New version of [validation](https://github.com/osrf/vrx/wiki/vrx_2022-validation)
* [x] New version of [submission process](https://github.com/osrf/vrx/wiki/submission_process)
* [x] Remove references to VRX 2023 for tutorials related to the _environment_ (these should now all be defaults or, if needed, VRX 2.0+)
* [x] Rename tutorials for VRX Classic to say "Classic"

Bumped to 2.3:
* #654
  * Requires significant work on vrx-docker.

**Comment by j-herman** [comment]
I am working first on the overview and placeholders/ links for the updated tutorials.  New tasks to follow.  If anyone is already working on some of these, please comment here so we don't double up.

**Comment by M1chaelM** [comment]
Tutorial Sequences:

### Getting Started
* System Requirements
* Install VRX
* Run VRX

### Getting Around
* Driving the WAMV
* Thruster Articulation
* Visual with Rviz

### Customize the WAMV (Beginner)
* Default Configuration
* Create Empty WAMV with generate_wamv.launch
* Customize Thruster Configuration
* Customize Components
* Compliance
* Non-Compliance

### Customize WAMV (Intermediate)
* Dynamics and Propulsion Characteristics
* TBD

### Customize the Environment
* Add Course Elements
* Changing the wind
* Changing the waves
* Fog and ambient light

**Comment by j-herman** [comment]
@M1chaelM Existing task tutorials are all updated (could use a second set of eyes to make sure I didn't miss any changes from last year).  The new tasks will take a little longer and may lag tomorrow's release by a day or so.

**Comment by M1chaelM** [comment]
@j-herman Thanks for finishing these up! For the next release my plan is to reorganize the layout a bit so it matches the tutorials for the VRX platform. When I do that I'll review what you have. We can also probably get some of our newest members to go through them so they will be sufficiently checked before the final release.

Given the above, I'm closing this issue as resolved.
