### ISSUE TITLE
Problem with renaming model_name

### ISSUE THREAD

**Issue by Grigoriy0526** [osrf/vrx#638]
Hello, I have a problem when starting the sydney_regatta world, if I rename model_name in the file competition.launch.py from 'wamv' to something else, an error occurs, what can such an error be related to?
![Снимок экрана от 2023-05-10 13-38-42](https://github.com/osrf/vrx/assets/133020151/3d2e6dbf-c637-4c5c-be9d-ed10e959c528)
![Снимок экрана от 2023-05-10 12-26-14](https://github.com/osrf/vrx/assets/133020151/fd3c4754-0f9a-40aa-82b7-573313237b66)

- Ubuntu 22.04
- ROS 2, Humble
- Gazebo Sim 7.0.0
-  VRX

**Comment by carvee1** [comment]
I solved the bug yesterday, when spawning a vehicle with another name, the problem can be found in  the `vrx_urdf/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro` file. In line 103, you have to change
 `<child>wamv/base_link</child>`
into 
 ` <child>$(arg namespace)/base_link</child>`
Afterwards it should work fine.
I already started the pull request #644  to solve this problem
Tested in ROS2 Humble and Ubuntu 22.04

**Comment by M1chaelM** [comment]
Thanks @Grigoriy0526 and @carvee1 for finding and fixing this!
Resolved with #644
