### ISSUE TITLE
wamv pinger (sensor) is listed as a component but no longer has visual or collision

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#641]
**Describe the bug**
Our `example_component_config.yaml` lists a pinger as a component of the WAMV, and our `wamv_gazebo.urdf.xacro` file suggests it is a component of the WAM-V (though it's default location is strange), but specifying its inclusion now has no effect because the collision and visual were removed in #566. Since the component is not actually required to receive messages from the broadcasting pinger, I'm not sure whether it should be mentioned or not. 

**Expected behavior**
Ideally, the pinger range_bearing topic would only be active if the WAM-V had an acoustic sensor enabled, an enabling it would cause it to show up as part of the WAMV's entity tree.

**To Reproduce**
List the steps to reproduce the problem:
1. Run 'ros2 launch vrx_gz competition.launch.py world:=sydney_regatta'
2. Look at the WAMV in the entity tree and notice there is no "pinger" listed.

**Comment by caguero** [comment]
Fixed in #669
