### ISSUE TITLE
Proofread VRX 2023 Documentation

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#652]
We now have version 1.1 of both our technical guide and task descriptions for VRX 2023. Before our final release, it would be good for someone to proofread both of these documents. Creating this issue here so we can track it with the milestone.

**Comment by caguero** [comment]
I volunteer  :+1:

**Comment by M1chaelM** [comment]
@caguero Apologies, this issue should have specified that it is for version 1.2 of the documents, since version 1.1 is already published. I will transfer your comments over. Just clarifying here also in case there are further changes / comments from others.

**Comment by j-herman** [comment]
@M1chaelM Could you put a link to the latest version in the meeting agenda so I can be sure I'm reviewing the right copy with any new comments?

**Comment by j-herman** [comment]
Reconfirming here - reviewed both docs, see comments for recommendations

**Comment by M1chaelM** [comment]
@caguero and @j-herman Most comments are now resolved. Please take a quick look at the outstanding comment threads.

**Comment by M1chaelM** [comment]
All comments resolved. Version 1.2 of both documents is ready for publication. No further changes to the rules, API or environmental envelopes is expected.

**Comment by M1chaelM** [comment]
oops, reopening to address https://github.com/osrf/vrx/pull/692
