### ISSUE TITLE
New Example Team image for VRX 2.0

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#655]
Our most recent example image is still running VRX Classic. See https://github.com/osrf/vrx-docker/tree/master/team_config

This should be renamed to example_team_2022. A new example team should be created that works with VRX 2.0.

**Comment by caguero** [comment]
Waiting for the tutorial.

**Comment by j-herman** [comment]
See draft PR [#60](https://github.com/osrf/vrx-docker/pull/60) and modified [tutorial](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_interactive)
jessicaherman/vrx-competitor-example:2023.v1 image has the simplest example, as shown in the tutorial.  jessicaherman/vrx-competitor-example:2023.v2 is the working example that checks the task message, moves the wamv, and publishes a landmark message for the perception task.

**Comment by j-herman** [comment]
PR 60 is merged.  The tutorial for building the container interactively is good to go.
We did not make a plan for the dockerfile tutorial.  I don't think that needs to go with a tagged build, but I can work on it if nobody else has started.

**Comment by M1chaelM** [comment]
Sounds good! It also fits in nicely with the kinds of issues we are assigning to 2.3.1.
