### ISSUE TITLE
Inquiry on tutorials to Use plugins for ROS 2 Humble

### ISSUE THREAD

**Issue by PhilipAmadasun** [osrf/vrx#679]
This inquiry is a continuation from (here) [https://github.com/osrf/vrx/issues/595]. Will there be a tutorial on how to apply the bouyancy and thruster plugins for custom Unmanned Sea Vehicle Models?

**Comment by caguero** [comment]
Please, see the "Maritime" section of the Gazebo tutorials. We've covered many topics there.

https://gazebosim.org/api/sim/8/tutorials.html
