### ISSUE TITLE
Configure osrf/vrx Dockerhub repository

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#69]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/69)) by Michael McCarrin (Bitbucket: [m1chaelm](https://bitbucket.org/%7B3c3f500d-bbf6-472c-b8f7-627e5eabc226%7D/)).**

----------------------------------------
New repository for new name (vrx) needs to be set up so it's linked to the bitbucket code. Content we want to keep from the old Dockerhub repo should be ported over. Autobuild should be set up to produce images when new releases are published. Since release 1.0 is already published, this will need to be built and pushed manually.

**Comment by caguero** [comment]
See https://github.com/osrf/vrx/pull/208

**Comment by M1chaelM** [comment]
Resolved with #208 but never closed. Now moot anyway because we no longer release Docker images with VRX compiled. This has been replaced with base images containing the correct dependencies, which are available in the [dockwater](https://github.com/Field-Robotics-Lab/dockwater) repository.
