### ISSUE TITLE
Gazebo crashing with violent WAM-V motion

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#690]

**Comment by caguero** [comment]
Updates:
  1. I managed to reproduce the crash without hitting any buoys. I did it spinning the WAM-V violently while braking and accelerating again causing some pitching.

**Comment by M1chaelM** [comment]
While testing #692 I also managed to produce a crash in the acoustic tracking task world while moving relatively slowly. After a number of collisions the WAMV seems to destabilize and eventually tilts sideways under the water and crashes the simulation. A wild guess, but I wonder if this might also have something to do with the tuning of the drag coefficients, as described by @tejalbarnwal in #689 . The WAMV seems to be sitting high on the water and when the thrust is strong its movement seems strange.

**Comment by caguero** [comment]
See a workaround patch in #706 .

**Comment by caguero** [comment]
Fixed in #706
