### ISSUE TITLE
Implement Competition Mode

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#693]
During the competition we don't publish debugging topics and scoring, so as to discourage teams from building solutions that rely on this information during the tasks. In VRX classic we called this "competition_mode" and enabled it by setting a parameter called `non_competition_mode` to `false`. We need to implement this functionality in VRX 2.0+. It would also be nice to eliminate the double-negative by calling the parameter `competition_mode` and setting it to `true` when we want it to be on.

To do this the argument needs to be added to the `competition.launch.py` and then handled appropriately.

**Comment by caguero** [comment]
Done in #710
