### ISSUE TITLE
RoboBoat Reference Models

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#704]
We need to produce 2 reference models for vehicles similar to those that might be used by competitors in RoboBoat.

**Comment by M1chaelM** [comment]
Example Vehicles from RoboBoat 2023:

![PXL_20230322_173139787](https://github.com/osrf/vrx/assets/8611855/591ec1f8-8e69-4155-920a-eaa400af0b8b)
![PXL_20230322_173150513](https://github.com/osrf/vrx/assets/8611855/47eec0da-3741-4564-9d5d-f6fd9df031a3)
![PXL_20230322_173207078](https://github.com/osrf/vrx/assets/8611855/1eb06496-bdc6-451c-9cc4-a564e082de0c)
![PXL_20230322_173217877](https://github.com/osrf/vrx/assets/8611855/65a265e4-e9d0-40f3-a333-bcd105d83a13)
![PXL_20230322_173225231](https://github.com/osrf/vrx/assets/8611855/79f3c3d4-3ba8-481b-914e-b4045fa5ee0a)
![PXL_20230322_173232859](https://github.com/osrf/vrx/assets/8611855/3b2ec8e0-450c-480d-88bb-5276d2188316)
![PXL_20230322_173242275](https://github.com/osrf/vrx/assets/8611855/8d38b5d8-d71c-4f1c-9db7-6ef2528c0ff9)
![PXL_20230322_173254509](https://github.com/osrf/vrx/assets/8611855/fe1c5f83-bee4-4e18-a354-0f14d3e3c8f5)
![PXL_20230322_184924661](https://github.com/osrf/vrx/assets/8611855/c6382287-24e5-4ff8-8f00-9a228b2a464f)
![PXL_20230322_185007737](https://github.com/osrf/vrx/assets/8611855/fcf27e50-10eb-49e6-9c02-29976e94071f)

**Comment by caguero** [comment]
@ColeOSRF , I loaded preliminary versions of your models in Gazebo. See my comments below:

### Roboboat01

Overall, it looks pretty good. 

![Screenshot from 2023-08-17 23-04-51](https://github.com/osrf/vrx/assets/1440739/605ce679-4cac-4702-aad3-5c624a21972c)

Can we change the reference frame to have +x pointing forward and +y pointing to the right? This is how it looks like now:

![Screenshot from 2023-08-17 22-37-15](https://github.com/osrf/vrx/assets/1440739/b4f11d26-4762-403f-858f-ff5bf43c8151)

Same suggestion for the thruster model if that's the case.

### Roboboat02

I see some rectangular artifact surrounding the boat.

![Screenshot from 2023-08-17 23-05-12](https://github.com/osrf/vrx/assets/1440739/970b6d3d-0c14-435e-b79e-76e6d939969b)

I only loaded the `roboboat02.dae` mesh but it loaded propellers. It looks like the third pontoons has a wrong offset as it's overlapping one of the other two pontoons.

![Screenshot from 2023-08-17 23-05-39](https://github.com/osrf/vrx/assets/1440739/1ca330cf-f68c-4117-b3ad-4501c7421884)

There's an upper circular platform on the top but it looks like it's floating, there's nothing connecting it to the main chassis.

![Screenshot from 2023-08-17 23-05-45](https://github.com/osrf/vrx/assets/1440739/18ed484e-8c45-4eea-8a50-05f1ad98bd4d)

Can we also apply the same transformation to the reference frame as the 01 model? This is how it looks like now:
![Screenshot from 2023-08-17 23-12-17](https://github.com/osrf/vrx/assets/1440739/0be55bf5-541f-4e80-935e-06ffaa6f607e)

Besides these comments, I'd say we're ready for textures

**Comment by caguero** [comment]
Do you think you could also create simple colliders for these models? I can convert them into SDF geometries if you send me the raw data somehow.

**Comment by ColeOSRF** [comment]
Boat02 was very wrong. Apparently all hidden objects were exported as well which is why there were so many erroneous objects. I've re-exported both meshes with these comments addressed. Working on the colliders now.

**Comment by ColeOSRF** [comment]
Colliders are up. The SDF files for each object are located in their respective folder here. The actual prop does not have a collider since it's contained within the collision for the thruster housing. 
https://drive.google.com/open?id=1P28vX7s2CV-aGfjso1tSag4V1fwmUHCh&usp=drive_fs

**Comment by caguero** [comment]
Thanks! All looks good from my side now.

![Screenshot from 2023-08-22 15-24-39](https://github.com/osrf/vrx/assets/1440739/5392e130-3ee6-4867-b364-9729023a09bd)

![Screenshot from 2023-08-22 15-33-35](https://github.com/osrf/vrx/assets/1440739/d8db8667-efca-4c93-91c4-d9a3430c776c)

![Screenshot from 2023-08-22 15-24-16](https://github.com/osrf/vrx/assets/1440739/d6678585-9768-46b4-aacc-bfd45ef2f32c)

We're ready for textures!

**Comment by caguero** [comment]
Update with the textures from Cole integrated:

![Screenshot from 2023-09-04 19-43-22](https://github.com/osrf/vrx/assets/1440739/5945a437-893b-4e8f-b48b-737d4a93629f)

![Screenshot from 2023-09-04 19-47-39](https://github.com/osrf/vrx/assets/1440739/de7bb41a-18a3-4c48-ac61-b26c18b48c53)

**Comment by caguero** [comment]
Update with CPU cases integrated:

![Screenshot from 2023-09-19 18-29-33](https://github.com/osrf/vrx/assets/1440739/dbf5c8e4-9694-41fb-b922-c100ef2cce4e)

![Screenshot from 2023-09-19 18-29-14](https://github.com/osrf/vrx/assets/1440739/3d9d793d-fbce-41bc-9f10-b615d6fe7167)

Thruster:

![Screenshot from 2023-09-15 20-39-29](https://github.com/osrf/vrx/assets/1440739/a1f4c534-1312-49b1-b971-fbbda9ee40c2)

**Comment by caguero** [comment]
Updated thruster looking a bit brighter

![screenshot_from_2023-09-22_17-18-56_480](https://github.com/osrf/vrx/assets/1440739/980bf153-b362-48c9-b263-6a879809044d)

**Comment by caguero** [comment]
Added in #758 and #759.
