### ISSUE TITLE
Improved Tutorial Sequence for Adjusting WAM-V Parameters

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#712]
Eventually we want to support the ability to (easily) add custom USV models to VRX. This will be especially important for RoboBoat support, but has already been requested by users in several issues. See
* #595 
* #487 

As a starting point, we should create a tutorial sequence explaining how to customize the hydrodynamic and propulsion characteristics of the WAMV. We currently have [a minimal overview of this topic here](https://github.com/osrf/vrx/wiki/wamv_params_tutorial). Let's expand it to show examples of changing these parameters, similar to our [environmental parameters sequence](https://github.com/osrf/vrx/wiki/env_params_tutorial).

Once this is resolved, the next step will be a tutorial sequence showing how to add a new model like the ones being created for RoboBoat (#704) and attach the necessary plugins to get it working in the simulation.

**Comment by caguero** [comment]
This is mostly covered now in the dedicated "Maritime" section in the Gazebo tutorials.

https://gazebosim.org/api/sim/8/tutorials.html
