### ISSUE TITLE
Backup solution for running VRX when fuel is down

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#721]
## Problem
Gazebo fuel is down a lot of the time. This is not usually a problem for users who have already run VRX and cached the issue, but it will cause VRX to fail for users who are running for the first time.

## Proposal
We need to provide another way for users to get the models they need to run VRX when fuel is down.

## Implementation
One way to do this would be to provide a zip file containing the necessary models and instructions for how to download it and unzip in the right place so Gazebo does not need to contact fuel. Initial attempts to take this approach have been unsuccessful and we don't know why. For some reason, Gazebo does not seem to recognize when models are installed by being copied directly from the local filesystem, as opposed to being downloaded from fuel.

## Testing
A solution to this problem should allow a user who has access to a zip file containing the needed models to copy them into place and launch VRX for the first time, even if they have no internet access.

**Comment by caguero** [comment]
I confirmed that Fuel is already running on S3 and we shouldn't experience availability issues.

I also backed up and wiped out my Fuel directory and relaunched VRX but I wasn't able to reproduce any issues. After that, I removed my my Fuel directory again and restored the original one and things worked without any redownload. I also confirmed that the sim doesn't require Internet connection when the models are already in your local cache.

**Comment by M1chaelM** [comment]
Given the resolution of #726, I wonder if the problem might have been related to switching the name from `fuel.gazebosim.org` to `fuel.ignitionrobotics.org`, since systems that went through this switch would have both directories stored under `fuel`. Although it would be interesting to know, I think we can close this now that Fuel has switched to S3 and no one can currently reproduce the problem.
