### ISSUE TITLE
Sensor update rates incorrect

### ISSUE THREAD

**Issue by ngxingyu** [osrf/vrx#722]
**Describe the bug**
The technical guide states the update rate of imu is 100hz and gps is 20hz, but currently both are 15 in wamv_gazebo
https://github.com/osrf/vrx/blob/7aeb71d88dc36c2bc271488fc37bab3736cea09d/vrx_urdf/wamv_gazebo/urdf/components/wamv_gps.xacro#L4
https://github.com/osrf/vrx/blob/7aeb71d88dc36c2bc271488fc37bab3736cea09d/vrx_urdf/wamv_gazebo/urdf/components/wamv_imu.xacro#L3

**Comment by caguero** [comment]
Thanks for reporting it, I confirm the issue. I'll create a fix soon.

**Comment by caguero** [comment]
See https://github.com/osrf/vrx/pull/723.

**Comment by caguero** [comment]
It should be fixed in #723 . Let us know otherwise. Thanks!
