### ISSUE TITLE
Error While Running VRX Tutorial

### ISSUE THREAD

**Issue by mthudaa** [osrf/vrx#729]
I have been install gazebo garden and ROS Humble locally in my computer. The installation was successfully, but when I launch the VRX sims after instalation from main repository I get some error.

![image](https://github.com/osrf/vrx/assets/60550345/6961e168-5c77-4003-ab59-b6de37f74e28)

I was change `GZ_VERSION` to `garden`, but its still error like that

**Comment by caguero** [comment]
Could you provide the extra information requested in the issue template please? System configuration, command to reproduce, etc.

**Comment by caguero** [comment]
Closing for now. Reopen if necessary providing extra information.
