### ISSUE TITLE
Wamv model not found

### ISSUE THREAD

**Issue by huiyulhy** [osrf/vrx#732]
**Describe the bug**
Please say what is broken. Include whether you think this is a problem with the code or the documentation / tutorials.
Running the standard competition command or command from custom WAMV to launch the simulation gives the following error on gazebo: `ros2 launch vrx_gz competition.launch.py world:=sydney_regatta`

Gazebo does not seem to be able to download the model of the WAMV - is there another way to download the meshes and place them into a directory?

**Expected behavior**
WAMV mesh should be downloaded and rendered, but the download does not seem to work. 

**To Reproduce**
Ran the same steps per the instructions on installing VRX and launching the competition environment.

**System Configuration:**
Tell us about your system.
- OS: Ubuntu 22.04
- ROS Version: Ros2 Humble
- Gazebo Version: Gazebo garden
- Graphics Card: Nvidia 1660 super
- Are you using VRX or VRX Classic? VRX

**Screenshots**
If applicable, add screenshots to help explain your problem. (If the problem is terminal output, it is better to cut and paste the text than to take a screenshot.)

**Additional notes**

**Comment by caguero** [comment]
Hi! I can't reproduce this error. WAM-V doesn't have to be downloaded, it's generated on the fly from URDF.

Could you paste the error message that you're getting?
Are you using the latest VRX version?

**Comment by huiyulhy** [comment]
Sorry I forgot to attach this earlier, here is a screenshot of the error - it seems like my computer is unable to fetch the meshes from the wamv folder and also the thruster folder. I had just recently (maybe 3 days again) cloned the main branch from VRX - is that the correct VRX version? 
![image](https://github.com/osrf/vrx/assets/26198479/a4c8d425-cf37-4ef2-b311-7894d4a6278c)

**Comment by caguero** [comment]
Could you share the output of this command?

```
env | grep GZ
```

**Comment by huiyulhy** [comment]
This is the output from my terminal for this command, thanks for helping me to troubleshoot this!
![image](https://github.com/osrf/vrx/assets/26198479/8777dbbb-d508-4e7e-a1f2-d2b3efa8866f)

**Comment by caguero** [comment]
The paths on `GZ_SIM_RESOURCE_PATH` look wrong. For instance, instead of:
`/home/lhy/vrx_ws/install/wamv_description/share/wamv_description/models`
you should have:
`/home/lhy/vrx_ws/install/share/wamv_description/models`

I wonder if you ran `colcon build` in the `vrx_ws` directory. My suggestion is to clear your workspace:
```
rm -rf build install log
```
Recompile again and in a new terminal source the appropriate `install/setup.bash`.

**Comment by jjeerryy** [comment]
Hi there,

I'm getting a different issue. I'm using WSL Ubuntu 22.04.
When I run the line ros2 launch vrx_gz competition.launch.py world:=sydney_regatta
I see the gazebo sim pop up like below and then nothing shows up and it closes itself. 
![image](https://github.com/osrf/vrx/assets/91396590/1bafa18c-76b3-4be9-96be-db459c4862c4)

I noticed there were a lot of 'server directory does not exist' when I first run the code.

Any idea why this is happening?

**Comment by huiyulhy** [comment]
This works great for me now. Thanks for helping me with troubleshooting!

**Comment by mvanlobensels** [comment]
How can I make Gazebo search in `install/wamv_description/share/wamv_description/models` instead?
