### ISSUE TITLE
ERROR while running Acoustic pinger_tutorial

### ISSUE THREAD

**Issue by Abivincii16** [osrf/vrx#738]
**Describe the bug**
Error with tutorials "Acoustic Beacon".
Error while trying to read acoustic beacon messages.
Getting warning messages while launching the gymkhana_task. 
Please say what is broken. Include whether you think this is a problem with the code or the documentation / tutorials.

**Expected behavior**
I was trying to read the data published by the acoustic sensor.

**To Reproduce**
Steps to reproduce the problem:
1. ros2 launch vrx_gz competition.launch.py world:=gymkhana_task
2. ros2 topic echo /wamv/pingers/pinger/range_bearing

**System Configuration:**
About my system.
- OS: Ubuntu 22.04
- ROS Version:  ROS 2, Humble
- Gazebo Version: Gazebo Sim 7.0.0
- Graphics Card: Nvidia GTX 1650
- I am using VRX .

**Screenshots**
![image](https://github.com/osrf/vrx/assets/102342856/3282045e-bd29-4b55-8a7a-a3ab7ca897cb)

**error message**
[Error_file.txt](https://github.com/osrf/vrx/files/12664479/Error_file.txt)

**Comment by tharakeshvar01** [comment]
Solution:
instead of :
ros2 topic echo /wamv/pingers/pinger/range_bearing
Run:
ros2 topic echo /wamv/sensors/acoustics/receiver/range_bearing
