### ISSUE TITLE
Cannot launch gazebo natively after run ros2 launch vrx_gz competition.launch.py world:=sydney_regatta

### ISSUE THREAD

**Issue by sontung1010** [osrf/vrx#755]
**Describe the bug**
Cannot launch gazebo natively after run ros2 launch vrx_gz competition.launch.py world:=sydney_regatta

**Expected behavior**
Launch the gazebo sim

**To Reproduce**
List the steps to reproduce the problem:
1. Following exactly the tutorial
2. Next, run ''ros2 launch vrx_gz competition.launch.py world:=sydney_regatta"
3. See error
4. Actually, to make gazebo appear with grid as in the screenshot, I have to open another gazebo window before I ran the command above. If not, it will stuck at "requesting a list of world name" after I followed exactly everything in the tutorial.

**System Configuration:**
Tell us about your system.
- OS: Ubuntu 22.04
- ROS Version: ROS 2, Humble
- Gazebo Version: Gazebo Sim 7.0.0
- Graphics Card: Nvidia GTX 3050 Ti
- Are you using VRX or VRX Classic? VRX

**Screenshots**
[
![Screenshot from 2023-12-04 18-22-17](https://github.com/osrf/vrx/assets/84949974/fcb3a016-47a6-48fa-a5ff-7d282c66e8d8)
](url)
[INFO] [launch]: All log files can be found below /home/st/.ros/log/2023-12-04-18-12-18-078183-Vivobook-4592
[INFO] [launch]: Default logging verbosity is set to INFO
['xacro', '/home/st/vrx_ws/install/share/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro', 'namespace:=wamv', 'locked:=true', 'vrx_sensors_enabled:=true', 'thruster_config:=H']
[INFO] [ruby $(which gz) sim-1]: process started with pid [4595]
[INFO] [monitor_sim-2]: process started with pid [4597]
[INFO] [create-3]: process started with pid [4600]
[INFO] [parameter_bridge-4]: process started with pid [4602]
[create-3] [INFO] [1701731538.723301016] [ros_gz_sim]: Requesting list of world names.
[parameter_bridge-4] [INFO] [1701731538.731529512] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/clock (ignition.msgs.Clock) -> /clock (rosgraph_msgs/msg/Clock)] (Lazy 0)
[parameter_bridge-4] [INFO] [1701731538.732229848] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/task/info (ignition.msgs.Param) -> /vrx/task/info (ros_gz_interfaces/msg/ParamVec)] (Lazy 0)
[parameter_bridge-4] [INFO] [1701731538.733393184] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/debug/wind/speed (ignition.msgs.Float) -> /vrx/debug/wind/speed (std_msgs/msg/Float32)] (Lazy 0)
[parameter_bridge-4] [INFO] [1701731538.733744940] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/debug/wind/direction (ignition.msgs.Float) -> /vrx/debug/wind/direction (std_msgs/msg/Float32)] (Lazy 0)
[create-3] [INFO] [1701731538.924726616] [ros_gz_sim]: Requested creation of entity.
[create-3] [INFO] [1701731538.924772254] [ros_gz_sim]: OK creation of entity.
[ruby $(which gz) sim-1] [Wrn] [LocalCache.cc:105] Server directory does not exist [/home/st/.gz/fuel/fuel.gazebosim.org]
[ruby $(which gz) sim-1] [Wrn] [LocalCache.cc:105] Server directory does not exist [/home/st/.gz/fuel/fuel.ignitionrobotics.org]
[INFO] [create-3]: process has finished cleanly [pid 4600]
[INFO] [optical_frame_publisher-5]: process started with pid [4686]
[INFO] [optical_frame_publisher-6]: process started with pid [4688]
[INFO] [optical_frame_publisher-7]: process started with pid [4690]
[INFO] [parameter_bridge-8]: process started with pid [4692]
[INFO] [pose_tf_broadcaster-9]: process started with pid [4694]
[INFO] [robot_state_publisher-10]: process started with pid [4696]
[parameter_bridge-8] [INFO] [1701731539.140072796] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/model/wamv/pose (ignition.msgs.Pose_V) -> /model/wamv/pose (tf2_msgs/msg/TFMessage)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.141905518] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/model/wamv/pose_static (ignition.msgs.Pose_V) -> /model/wamv/pose_static (tf2_msgs/msg/TFMessage)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.142232116] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/joint_state (ignition.msgs.Model) -> /world/sydney_regatta/model/wamv/joint_state (sensor_msgs/msg/JointState)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.143190718] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/contacts (ignition.msgs.Contacts) -> /vrx/contacts (ros_gz_interfaces/msg/Contacts)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.144171674] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.144552926] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.145016237] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.145294411] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.145592254] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan (ignition.msgs.LaserScan) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan (sensor_msgs/msg/LaserScan)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.145958307] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan/points (ignition.msgs.PointCloudPacked) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan/points (sensor_msgs/msg/PointCloud2)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.146451545] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.146747624] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.147016872] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/gps_wamv_link/sensor/navsat/navsat (ignition.msgs.NavSat) -> /world/sydney_regatta/model/wamv/link/wamv/gps_wamv_link/sensor/navsat/navsat (sensor_msgs/msg/NavSatFix)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.147362987] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/imu_wamv_link/sensor/imu_wamv_sensor/imu (ignition.msgs.IMU) -> /world/sydney_regatta/model/wamv/link/wamv/imu_wamv_link/sensor/imu_wamv_sensor/imu (sensor_msgs/msg/Imu)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.147687631] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/left/thrust (std_msgs/msg/Float64) -> wamv/thrusters/left/thrust (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.148191599] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/left/pos (std_msgs/msg/Float64) -> wamv/thrusters/left/pos (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.148496475] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/right/thrust (std_msgs/msg/Float64) -> wamv/thrusters/right/thrust (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.148774540] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/right/pos (std_msgs/msg/Float64) -> wamv/thrusters/right/pos (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.149053796] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [wamv/sensors/acoustics/receiver/range_bearing (ignition.msgs.Param) -> wamv/sensors/acoustics/receiver/range_bearing (ros_gz_interfaces/msg/ParamVec)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.149416483] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [/pinger/set_pinger_position (geometry_msgs/msg/Vector3) -> /pinger/set_pinger_position (ignition.msgs.Vector3d)] (Lazy 0)
[parameter_bridge-8] [INFO] [1701731539.149840939] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [/wamv/shooters/ball_shooter/fire (std_msgs/msg/Bool) -> /wamv/shooters/ball_shooter/fire (ignition.msgs.Boolean)] (Lazy 0)
[robot_state_publisher-10] [WARN] [1701731539.152743939] [kdl_parser]: The root link wamv/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-10] [INFO] [1701731539.152886082] [wamv.robot_state_publisher]: got segment wamv/ball_shooter_base_link
[robot_state_publisher-10] [INFO] [1701731539.152941188] [wamv.robot_state_publisher]: got segment wamv/ball_shooter_launcher_link
[robot_state_publisher-10] [INFO] [1701731539.152946828] [wamv.robot_state_publisher]: got segment wamv/base_link
[robot_state_publisher-10] [INFO] [1701731539.152950666] [wamv.robot_state_publisher]: got segment wamv/cpu_cases_link
[robot_state_publisher-10] [INFO] [1701731539.152954173] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_link
[robot_state_publisher-10] [INFO] [1701731539.152957639] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_link_optical
[robot_state_publisher-10] [INFO] [1701731539.152961126] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1701731539.152964543] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_post_link
[robot_state_publisher-10] [INFO] [1701731539.152967989] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_link
[robot_state_publisher-10] [INFO] [1701731539.152971456] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_link_optical
[robot_state_publisher-10] [INFO] [1701731539.152974862] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1701731539.152978479] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_post_link
[robot_state_publisher-10] [INFO] [1701731539.152981886] [wamv.robot_state_publisher]: got segment wamv/gps_wamv_link
[robot_state_publisher-10] [INFO] [1701731539.152985373] [wamv.robot_state_publisher]: got segment wamv/imu_wamv_link
[robot_state_publisher-10] [INFO] [1701731539.152988749] [wamv.robot_state_publisher]: got segment wamv/left_battery_link
[robot_state_publisher-10] [INFO] [1701731539.152992246] [wamv.robot_state_publisher]: got segment wamv/left_engine_link
[robot_state_publisher-10] [INFO] [1701731539.152995732] [wamv.robot_state_publisher]: got segment wamv/left_propeller_link
[robot_state_publisher-10] [INFO] [1701731539.152999189] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_link
[robot_state_publisher-10] [INFO] [1701731539.153003618] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_post_arm_link
[robot_state_publisher-10] [INFO] [1701731539.153007255] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_post_link
[robot_state_publisher-10] [INFO] [1701731539.153010631] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_link
[robot_state_publisher-10] [INFO] [1701731539.153014028] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_link_optical
[robot_state_publisher-10] [INFO] [1701731539.153017685] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1701731539.153021111] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_post_link
[robot_state_publisher-10] [INFO] [1701731539.153024508] [wamv.robot_state_publisher]: got segment wamv/receiver
[robot_state_publisher-10] [INFO] [1701731539.153028025] [wamv.robot_state_publisher]: got segment wamv/right_battery_link
[robot_state_publisher-10] [INFO] [1701731539.153031651] [wamv.robot_state_publisher]: got segment wamv/right_engine_link
[robot_state_publisher-10] [INFO] [1701731539.153035299] [wamv.robot_state_publisher]: got segment wamv/right_propeller_link
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [Msg] Gazebo Sim GUI    v7.6.0
[ruby $(which gz) sim-1] [Dbg] [Gui.cc:261] Waiting for subscribers to [/gazebo/starting_world]...
[ruby $(which gz) sim-1] [Dbg] [Application.cc:96] Initializing application.
[ruby $(which gz) sim-1] [Dbg] [Application.cc:128] Qt using OpenGL graphics interface
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:607] Create main window
[ruby $(which gz) sim-1] [GUI] [Dbg] [PathManager.cc:67] Requesting resource paths through [/gazebo/resource_paths/get]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Gui.cc:341] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ruby $(which gz) sim-1] [GUI] [Dbg] [PathManager.cc:56] Received resource paths.
[ruby $(which gz) sim-1] [GUI] [Dbg] [Gui.cc:399] Requesting GUI from [/world/default/gui/info]...
[ruby $(which gz) sim-1] [GUI] [Dbg] [GuiRunner.cc:149] Requesting initial state from [/world/default/state]...
[ruby $(which gz) sim-1] [GUI] [Msg] Loading config [/home/st/.gz/sim/7/gui.config]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [MinimalScene]
[ruby $(which gz) sim-1] [GUI] [Dbg] [MinimalScene.cc:657] Creating gz-rendering interface for OpenGL
[ruby $(which gz) sim-1] [GUI] [Dbg] [MinimalScene.cc:657] Creating gz-rendering interface for OpenGL
[ruby $(which gz) sim-1] [GUI] [Dbg] [MinimalScene.cc:817] Creating render thread interface for OpenGL
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [3D View] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [MinimalScene] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libMinimalScene.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [EntityContextMenuPlugin]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Entity Context Menu] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [EntityContextMenuPlugin] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libEntityContextMenuPlugin.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [GzSceneManager]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Scene Manager] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [GzSceneManager] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libGzSceneManager.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [InteractiveViewControl]
[ruby $(which gz) sim-1] [GUI] [Msg] Camera view controller topic advertised on [/gui/camera/view_control]
[ruby $(which gz) sim-1] [GUI] [Msg] Camera reference visual topic advertised on [/gui/camera/view_control/reference_visual]
[ruby $(which gz) sim-1] [GUI] [Msg] Camera view control sensitivity advertised on [/gui/camera/view_control/sensitivity]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Interactive view control] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [InteractiveViewControl] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libInteractiveViewControl.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [CameraTracking]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Camera tracking] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [CameraTracking] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libCameraTracking.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [MarkerManager]
[ruby $(which gz) sim-1] [GUI] [Msg] Listening to stats on [/world/default/stats]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Marker Manager] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [MarkerManager] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libMarkerManager.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [SelectEntities]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Select entities] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [SelectEntities] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libSelectEntities.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [Spawn]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Spawn] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [Spawn] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libSpawn.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [VisualizationCapabilities]
[ruby $(which gz) sim-1] [GUI] [Msg] View as transparent service on [/gui/view/transparent]
[ruby $(which gz) sim-1] [GUI] [Msg] View as wireframes service on [/gui/view/wireframes]
[ruby $(which gz) sim-1] [GUI] [Msg] View center of mass service on [/gui/view/com]
[ruby $(which gz) sim-1] [GUI] [Msg] View inertia service on [/gui/view/inertia]
[ruby $(which gz) sim-1] [GUI] [Msg] View collisions service on [/gui/view/collisions]
[ruby $(which gz) sim-1] [GUI] [Msg] View joints service on [/gui/view/joints]
[ruby $(which gz) sim-1] [GUI] [Msg] View frames service on [/gui/view/frames]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Visualization capabilities] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [VisualizationCapabilities] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libVisualizationCapabilities.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [WorldControl]
[ruby $(which gz) sim-1] [GUI] [Msg] Using world control service [/world/default/control]
[ruby $(which gz) sim-1] [GUI] [Msg] Listening to stats on [/world/default/stats]
[ruby $(which gz) sim-1] [GUI] [Dbg] [WorldControl.cc:250] Using an event to share WorldControl msgs with the server
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [World control] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [WorldControl] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libWorldControl.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [WorldStats]
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityTree/EntityTree.qml:148:7: QML ToolButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Component.hh:189] Trying to deserialize component with data type [N3sdf3v135WorldE], which doesn't have `operator>>`. Component will not be deserialized.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Component.hh:172] Trying to deserialize component with data type [St10shared_ptrIN3sdf3v137ElementEE], which doesn't have `operator>>`. Component will not be deserialized.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityTree/EntityTree.qml:148:7: QML ToolButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/WorldStats/WorldStats.qml:53:3: QML RowLayout: Binding loop detected for property "x"
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Wrn] [Application.cc:859] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ruby $(which gz) sim-1] [GUI] [Msg] Listening to stats on [/world/default/stats]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [World stats] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [WorldStats] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libWorldStats.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [Shapes]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Shapes] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [Shapes] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libShapes.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [Lights]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Lights] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [Lights] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libLights.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [TransformControl]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Transform control] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [TransformControl] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libTransformControl.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [Screenshot]
[ruby $(which gz) sim-1] [GUI] [Msg] Screenshot service on [/gui/screenshot]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Screenshot] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [Screenshot] from path [/usr/lib/x86_64-linux-gnu/gz-gui-7/plugins/libScreenshot.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [CopyPaste]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Copy/Paste] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [CopyPaste] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libCopyPaste.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [ComponentInspector]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Component inspector] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [ComponentInspector] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libComponentInspector.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:459] Loading plugin [EntityTree]
[ruby $(which gz) sim-1] [GUI] [Msg] Added plugin [Entity tree] to main window
[ruby $(which gz) sim-1] [GUI] [Msg] Loaded plugin [EntityTree] from path [/usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/gui/libEntityTree.so]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:329] Loading window config
[ruby $(which gz) sim-1] [GUI] [Msg] Using server control service [/server_control]
[ruby $(which gz) sim-1] [GUI] [Dbg] [Application.cc:621] Applying config
[ruby $(which gz) sim-1] [GUI] [Dbg] [MinimalScene.cc:657] Creating gz-rendering interface for OpenGL
[ruby $(which gz) sim-1] libEGL warning: egl: failed to create dri2 screen
[ruby $(which gz) sim-1] libEGL warning: egl: failed to create dri2 screen

**Comment by j-herman** [comment]
Hi @sontung1010,

Are you still seeing this issue?  If so, I have a few questions that may help with troubleshooting:

Could you post the output you see when you don't open a gazebo window before trying to start VRX?  I'll take a look.
Did you have an earlier version of Gazebo installed on this computer before upgrading to 7.0?  
Are you able to run other worlds that include models from Fuel?

**Comment by sontung1010** [comment]
actually, I found a way to work around, thank you.

**Comment by 6678lin** [comment]
Hello, may I ask how you solved this problem? I also met such a situation.

**Comment by sontung1010** [comment]
I am not sure, the next time I ran it worked perfectly fine. So maybe do a clean install from the beginning or even reinstall ubuntu
