### ISSUE TITLE
Running ROS 2 Gazebo Garden on Windows 11 with Docker image

### ISSUE THREAD

**Issue by sontung1010** [osrf/vrx#756]
Hello, I have a laptop with Windows 11 and Nvidia GPU. Has anyone succeeded in running the latest version of VRX with ROS 2 and Gazebo Garden on Windows 11 using the docker image? I am considering running it on my machine or finding a native Ubuntu option. Thanks.

**Comment by caguero** [comment]
Your configuration isn't one of the recommended setups. You can try asking these type of questions on [Robotics](https://robotics.stackexchange.com/)
