### ISSUE TITLE
How to change buoyancy configuration to make my model float

### ISSUE THREAD

**Issue by sontung1010** [osrf/vrx#761]
I load my own .stl model into the project and I want to know which files/parameters to adjust to make my model usable. Thank you very much.

**Describe the bug**
It is sinking too much
![Screenshot from 2023-12-23 13-22-47](https://github.com/osrf/vrx/assets/84949974/2da4738a-172c-4037-ae96-15932c2f13df)

**Expected behavior**
I want it to be visible on the surface like this all the time
![Screenshot from 2023-12-23 13-23-08](https://github.com/osrf/vrx/assets/84949974/76190247-0a89-46b3-a6a7-b2f25a1cd031)

**System Configuration:**
Tell us about your system.
- OS: Ubuntu 22.04
- ROS Version: ROS 2, Humble
- Gazebo Version: Gazebo Sim 7.0.0
- Are you using VRX or VRX Classic? VRX

**Comment by caguero** [comment]
I recommend to go through this tutorial from Gazebo to learn about the `Surface` plugin and how to modify its parameters.

https://gazebosim.org/api/sim/8/surface_vehicles.html

**Comment by sontung1010** [comment]
Hello, I got everything worked. But now I am trying to add my function to the repo but I am not sure which is the main root file that everything starts from. Can you please show me that or something like a hierarchy of the program repo? Thank you very much.

**Comment by Roboticistprogrammer** [comment]
Hey there @sontung1010, would you mind sharing how you add your .stl model?
I was wandering if I should use **generate_wamv.launch.py** to generate urdf file, or just add my model using /mesh within one of the worlds provided. e.g:
<geometry>
   <mesh filename="package:// ~/Path_To_My_File/XX.stl"/>
</geometry>
