### ISSUE TITLE
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: No module named 'sdformat13'

### ISSUE THREAD

**Issue by liye20001228** [osrf/vrx#762]
When run the 'ros2 launch vrx_gz competition.launch.py world:=sydney_regatta'
', a trouble occur as: [ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: No module named 'sdformat13

**Comment by caguero** [comment]
You probably forgot to install `python3-sdformat13`.

```
sudo apt install python3-sdformat13
```

See https://github.com/osrf/vrx/wiki/preparing_system_tutorial
