### ISSUE TITLE
What kind of surface water features are available in this framework ?

### ISSUE THREAD

**Issue by vbalaji21** [osrf/vrx#770]
I would like to know what kind of surface water effects are available in this framework ?
I guess buoyancy, drag is present. I would like to know whether wave effects are also present ?

**Comment by caguero** [comment]
Here's a quick summary:

* Surface plugin: it provides drag and buoyancy to the vehicle, and simulates the physics of waves acting on the vehicle.
* Thruster plugin: it provides thrust to the vehicle.
* WaveVisual: it renders the wave visuals.
