### ISSUE TITLE
Error while following tutorials thruster_component_config.

### ISSUE THREAD

**Issue by b0jji** [osrf/vrx#771]
I need to create a custom URDF file for a WAM-V but when I followed the tutorial at https://github.com/osrf/vrx/wiki/tutorials-thruster_component_config exactly, I got the following error message:

FileNotFoundError: [Errno 2] No such file or directory: '/home/b0jji/my_wamv/thruster_config.xacro'.

According to the tutorial, this is not supposed to happen as the inputs for this script are "component_config.yaml" and "thruster_config.yaml" only. No mention of an xacro file whatsoever.

The script reads the "component_config.yaml" but not the "thruster_config.yaml" as it is looking for an xacro file instead.

Edit:
Upon further inspection, I realized that need for an .xacro file might be expected but the script is failing to create a proper .xacro file. Here is the "thruster_config.xacro" the script created:

`<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="wam-v-thrusters">
  <xacro:include filename="$(find wamv_description)/urdf/thrusters/engine.xacro" />
`

It fails to close the <robot> tag which might cause the problem.

**Comment by caguero** [comment]
I think you're looking at a tutorial from the Gazebo Classic version. Could you trying these ones?

https://github.com/osrf/vrx/wiki/tutorials#customizing-the-wam-v-beginner
