### ISSUE TITLE
joint unit

### ISSUE THREAD

**Issue by gami0321** [osrf/vrx#775]
Is the unit of velocity for the propeller joint of the WAM-V model rad/s or m/s?

**Comment by caguero** [comment]
If you introspect Gazebo to read the angular velocity of the propeller joint is `rad/s`. If you subscribe to the Gazebo topic associated to the thruster (`/wamv/thrusters/right/thrust/ang_vel`) it's also `rad/s`. Note that this topic is not bridged into ROS.
